### ISSUE TITLE
Подключить react-hook-form в form.js

### ISSUE THREAD

**Issue by slavb18** [iconicompany/nextjs-semantic#1]
1. Запустить проект, посмотреть как работает [autoform](localhost:3000/autoform): при нажатии кнопки происходит переход по url autoform [с заполненными параметрами](http://localhost:3000/autoform?firstName=Ivan&lastName=Petrov&workExperience=55)  
1. Изучить  https://react-hook-form.com/
1. Подключить react-hook-form в [pages/form.js](../blob/master/pages/form.js)
1. Релизовать форму, аналогичную autoform, вручную [на компонентах semantic](https://react.semantic-ui.com/collections/form/)
1. Написать submitHandler, выполняющий переход на form с параметрами
```
function onSubmit(query) {
    router.push({ pathname: 'form', query });
  }
```

Для справки см. поведение  [pages/autoform.js](../blob/master/pages/autoform.js) и [Обзор библиотеки uniforms](https://youtu.be/mS73pBO07DA)

**Comment by puphs** [comment]
В form.js должна быть форма, такая же, как и в autoform.js. Отправка и валидация должны быть реализованы с помощью react-hook-form. Сама форма должна быть построена из компонентов semantic.
Я правильно понял?

**Comment by slavb18** [comment]
Да, все верно. В данном задании изучаем автоматические и ручные формы React.
